#!/bin/bash
#
# emacs-anywhere - use Emacs whenever, wherever
# Author: Prathik Raj
# Homepage: https://www.github.com/prathik/emacs-anywhere
#
# Installs emacs-anywhere. Intended for use via curl:
#
#   $ curl -fsSL https://raw.github.com/prathik/emacs-anywhere/master/install | bash

set -e

###
# opts
###

while getopts ":v" opt; do
  case "$opt" in
    v) set -x ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

###
# defs
###

err() { echo -e "$@" 1>&2; }

check_installed() { hash $1 &> /dev/null; }

require_installed() {
  if ! check_installed $1; then
    err "emacs-anywhere requires $1 to function"
    if [[ "$2" != "" ]]; then echo $2; fi
    exit 1
  fi
}

require_one_installed() {
  for file in $*; do
    check_installed $file && return
  done
  err "emacs-anywhere requires one of the following to be installed:\n$*"
  exit 1
}

AW_PATH=$HOME/.emacs-anywhere
AW_URL='https://github.com/prathik/emacs-anywhere'

###
# pre-installation checks
###

# Check if emacs-anywhere is already installed. If so, remove the previous
# installation.
if [ -a $AW_PATH ]; then
  echo 'Cleaning up previous installation...'
  rm -rf $AW_PATH
  # TODO: It would be nice to have an option for user input here
  # Reinstall emacs-anywhere (y/n)? ... or something like that
fi

require_installed git

# if we are in a git repo, unset env vars
if git rev-parse --git-dir &> /dev/null; then
  unset $(git rev-parse --local-env-vars) &> /dev/null
fi

if [[ $OSTYPE == "darwin"* ]]; then
    require_installed emacs 'Run `brew install emacs --with-cocoa`.'

    # Check for Emacs with GUI support
    if ! open -a Emacs --args --eval "(kill-emacs)"; then
	echo 'Emacs has not been installed with GUI support'
	echo 'Please run brew install emacs --with-cocoa'
	exit 1
    fi
# Unsupported OS
else
  echo "OS '$OSTYPE' is not supported!"
  exit 1
fi

###
# installation
###

echo "Installing emacs-anywhere..."

git clone $AW_URL $AW_PATH

# OSX install
if [[ $OSTYPE == "darwin"* ]]; then
  # store the absolute path to the mvim executable
  which emacs > $AW_PATH/.path

  # install the workflow as a service
  mkdir -p $HOME/Library/Services
  cp -R $AW_PATH/EmacsAnywhere.workflow $HOME/Library/Services

  # TODO: add shortcut
  # It would be great if there was a way to set the keyboard shortcut for
  # emacs-anywhere programatically (without GUI scripting). If there ends up being a
  # way to do this, it would go here.

  # As a partial workaround, run a script that opens the shortcut options
  echo "Opening System Preferences..."
  osascript $AW_PATH/script/open_shortcuts.scpt &> /dev/null
fi

echo "emacs-anywhere has been successfully installed!"
