#!/bin/bash
#
# emacs-anywhere - use Emacs whenever, wherever
# Author: Prathik Raj
# Homepage: https://www.github.com/prathik/emacs-anywhere
#
# Uninstalls emacs-anywhere

set -e

###
# opts
###

while getopts ":v" opt; do
  case "$opt" in
    v) set -x ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

###
# defs
###

check_installed() { hash $1 &> /dev/null; }

AW_PATH=$HOME/.emacs-anywhere
DOC_PATH=/tmp/emacs-anywhere

###
# uninstall
###

rm -rf $AW_PATH $DOC_PATH

# OSX uninstall
if [[ $OSTYPE == "darwin"* ]]; then
  rm -rf $HOME/Library/Services/EmacsAnywhere.workflow
fi

echo "emacs-anywhere has been successfully uninstalled!"
