#!/bin/bash
#
# emacs-anywhere - use Emacs whenever, wherever
# Author: Prathik Raj
# Homepage: https://www.github.com/prathik/emacs-anywhere
#
# Updates emacs-anywhere

set -e

###
# opts
###

while getopts ":v" opt; do
  case "$opt" in
    v) set -x ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

###
# defs
###

err() { echo -e "$@" 1>&2; }

AW_PATH=$HOME/.emacs-anywhere

###
# update
###

if [ ! -d $AW_PATH ]; then
  err "emacs-anywhere doesn't seem to be installed."
  exit 1
fi

# if we are in a git repo, unset env vars
if git rev-parse --git-dir &> /dev/null; then
  unset $(git rev-parse --local-env-vars) &> /dev/null
fi

pushd $AW_PATH
  git pull origin master
  [ $? -ne 0 ] && exit 1
popd

# OSX only
if [[ $OSTYPE == "darwin"* ]]; then
  cp -R $AW_PATH/EmacsAnywhere.workflow $HOME/Library/Services
fi

echo "emacs-anywhere has been successfully updated!"
